print("Welcome! This program will calculate the circumfrance and area of a circle!")
radius = float(input("Enter the radius of your circle: "))
circumfrance = (radius*2*3.14)
area = (radius*radius*3.14)
circumfranceRounded = round(circumfrance, 2)
areaRounded = round(area, 2)
print("The circumfrance is", circumfranceRounded)
print("The area is", areaRounded)
print("Thank you for using my program!")
