print("Welcome! This program will calculate the circumfrance and area of a circle!")
unit = input("Enter the unit you are using (mm, cm, m, etc.): ")
radius = float(input("Enter the radius of your circle: "))
circumfrance = (radius*2*3.14)
area = (radius*radius*3.14)
circumfranceRounded = round(circumfrance, 2)
areaRounded = round(area, 2)
print("The circumfrance is", circumfranceRounded, unit)
print("The area is", areaRounded, unit)
print("Thank you for using my program!")
